CREATE TABLE MEASURES (
  MEASURE_ID NUMBER NOT NULL,
  MEASURE_NAME NVARCHAR2(20),
  CONSTRAINT PK_MEASURES PRIMARY KEY (MEASURE_ID)
)

CREATE TABLE VENDORS (
  VENDOR_ID NUMBER NOT NULL,
  VENDOR_NAME NVARCHAR2(50),
  CONSTRAINT PK_VENDORS PRIMARY KEY (VENDOR_ID)
)

CREATE TABLE PRODUCTS (
  PRODUCT_ID NUMBER NOT NULL, 
  VENDOR_ID CONSTRAINT FK_VENDOR_ID
    REFERENCES VENDORS(VENDOR_ID),
  PRODUCT_NAME NVARCHAR2(100) NOT NULL,
  MEASURE_ID CONSTRAINT FK_MEASURE_ID
    REFERENCES MEASURES(MEASURE_ID),
  PRICE NUMBER(9, 2) NOT NULL,
  CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
)

CREATE TABLE SALES (
  SALE_ID NUMBER NOT NULL,
  PRODUCT_ID CONSTRAINT FK_PRODUCT_ID
    REFERENCES PRODUCTS(PRODUCT_ID),
  QUANTITY NUMBER NOT NULL,
  DATE_SALE DATE NOT NULL
)

CREATE SEQUENCE PRODUCT_ID_SEQ
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE VENDOR_ID_SEQ
START WITH 10
INCREMENT BY 10

CREATE SEQUENCE MEASURE_ID_SEQ
START WITH 100
INCREMENT BY 100

CREATE SEQUENCE SALE_ID_SEQ
START WITH 1000
INCREMENT BY 1

INSERT INTO MEASURES 
VALUES (MEASURE_ID_SEQ.NEXTVAL, 'liters')

INSERT INTO MEASURES 
VALUES (MEASURE_ID_SEQ.NEXTVAL, 'pieces')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Zagorka Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Nestle Sofia Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Chipita Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Frito-Lay Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Lavazza Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Coca-Cola Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Prestige96 Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Pringles Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Vereya Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Casa Bella Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Bonne Maman Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'MIO Corp.')

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 10, 'Beer Zagorka', 100, 0.90)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Chocolate Milka', 200, 1.89)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Chocolate Milka Special', 200, 1.89)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 30, 'Croissant 7 days', 200, 0.90)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 70, 'Waffle Hiper', 200, 0.60)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 30, 'Cake 7 days', 200, 1.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 60, 'Coca-Cola 0.5l', 100, 1.30)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 60, 'Coca-Cola 2l', 100, 2.50)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 60, 'Sprite', 100, 1.30)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 40, 'Chips Lays', 200, 1.80)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 80, 'Chips Pringles', 200, 3.20)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 90, 'Yoghurt Vereya', 100, 1.00)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 90, 'Milk Vereya 3.6%', 100, 2.00)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 100, 'Pasta Casa Bella', 200, 2.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 120, 'Bread Dobrudza', 200, 0.90)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 30, 'Bake Rolls', 200, 0.90)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 110, 'Confiture Bonne Maman', 200, 3.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 110, 'Jelee Bonne Maman', 200, 3.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 40, 'Chips Ruffles', 200, 2.80)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 50, 'Caffee Lavazza', 200, 6.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Nescafe 3in1', 200, 0.40)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Nestle LZ', 200, 0.90)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Nestle Fitness', 200, 3.50)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 20, 'Ice Cream Aloma', 100, 3.80)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 10, 'Beer Becks', 100, 1.00)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 2, 3, TO_DATE('20/02/2015 15:55', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 10, 1, TO_DATE('20/02/2015 16:15', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 16, 3, TO_DATE('20/02/2015 16:23', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 21, 10, TO_DATE('15/02/2015 16:32', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 18, 1, TO_DATE('15/02/2015 16:45', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 5, 2, TO_DATE('20/01/2015 16:59', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 12, 2, TO_DATE('20/01/2015 17:03', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 24, 1, TO_DATE('20/01/2015 17:13', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 17, 1, TO_DATE('11/01/2015 17:14', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 14, 2, TO_DATE('11/01/2015 17:21', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 25, 5, TO_DATE('11/01/2015 17:25', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 12, 2, TO_DATE('22/03/2015 17:30', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 9, 2, TO_DATE('22/03/2015 17:43', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 15, 4, TO_DATE('22/03/2015 17:47', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 7, 1, TO_DATE('27/02/2015 17:54', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 23, 2, TO_DATE('01/02/2015 17:57', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 6, 3, TO_DATE('02/02/2015 18:01', 'dd/mm/yyyy hh24:mi'))

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 11, 1, TO_DATE('07/02/2015 18:11', 'dd/mm/yyyy hh24:mi'))
