CREATE TABLE MEASURES (
  MEASURE_ID NUMBER NOT NULL,
  MEASURE_NAME NVARCHAR2(20),
  CONSTRAINT PK_MEASURES PRIMARY KEY (MEASURE_ID)
)

CREATE TABLE VENDORS (
  VENDOR_ID NUMBER NOT NULL,
  VENDOR_NAME NVARCHAR2(50),
  CONSTRAINT PK_VENDORS PRIMARY KEY (VENDOR_ID)
)

CREATE TABLE LOCATIONS (
  LOCATION_ID NUMBER NOT NULL,
  LOCATION_NAME NVARCHAR2(50),
  CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID)
)

CREATE TABLE PRODUCTS (
  PRODUCT_ID NUMBER NOT NULL, 
  VENDOR_ID CONSTRAINT FK_VENDOR_ID
    REFERENCES VENDORS(VENDOR_ID),
  PRODUCT_NAME NVARCHAR2(100) NOT NULL,
  MEASURE_ID CONSTRAINT FK_MEASURE_ID
    REFERENCES MEASURES(MEASURE_ID),  
  CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
)

CREATE TABLE SALES (
  SALE_ID NUMBER NOT NULL,
  PRODUCT_ID CONSTRAINT FK_PRODUCT_ID
    REFERENCES PRODUCTS(PRODUCT_ID),
  LOCATION_ID CONSTRAINT FK_LOCATION_ID
    REFERENCES LOCATIONS(LOCATION_ID),
  QUANTITY NUMBER NOT NULL,
  DATE_SALE DATE NOT NULL,
  PRICE_PER_UNIT NUMBER(9, 2) NOT NULL
)

CREATE SEQUENCE PRODUCT_ID_SEQ
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE VENDOR_ID_SEQ
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE LOCATION_ID_SEQ
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE MEASURE_ID_SEQ
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE SALE_ID_SEQ
START WITH 1
INCREMENT BY 1

INSERT INTO MEASURES 
VALUES (MEASURE_ID_SEQ.NEXTVAL, 'liters')

INSERT INTO MEASURES 
VALUES (MEASURE_ID_SEQ.NEXTVAL, 'pieces')

INSERT INTO MEASURES 
VALUES (MEASURE_ID_SEQ.NEXTVAL, 'kg')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Zagorka Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Nestle Sofia Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Chipita Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Frito-Lay Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Lavazza Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Coca-Cola Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Prestige96 Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Pringles Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Vereya Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Casa Bella Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Bonne Maman Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'MIO Corp.')

INSERT INTO VENDORS 
VALUES (VENDOR_ID_SEQ.NEXTVAL, 'Targovishte Bottling Company Ltd.')

INSERT INTO LOCATIONS 
VALUES (LOCATION_ID_SEQ.NEXTVAL, 'Supermarket "Baba Meca" Kulata')

INSERT INTO LOCATIONS 
VALUES (LOCATION_ID_SEQ.NEXTVAL, 'Supermarket "Kumcho Vulcho" Chelopechene')

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 1, 'Beer Zagorka', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 1, 'Beer Becks', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 13, 'Vodka Targovishte', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Chocolate Milka', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Chocolate Milka Special', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 3, 'Croissant 7 days', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 7, 'Waffle Hiper', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 3, 'Cake 7 days', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 6, 'Coca-Cola 0.5l', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 6, 'Coca-Cola 2l', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 6, 'Sprite', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 4, 'Chips Lays', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 8, 'Chips Pringles', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 9, 'Yoghurt Vereya', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 9, 'Milk Vereya 3.6%', 1)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 10, 'Pasta Casa Bella', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 12, 'Bread Dobrudza', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 3, 'Bake Rolls', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 11, 'Confiture Bonne Maman', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 11, 'Jelee Bonne Maman', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 4, 'Chips Ruffles', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 5, 'Caffee Lavazza', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Nescafe 3in1', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Nestle LZ', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Nestle Fitness', 2)

INSERT INTO PRODUCTS 
VALUES (PRODUCT_ID_SEQ.NEXTVAL, 2, 'Ice Cream Aloma', 1)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 2, 1, 3, TO_DATE('20/02/2015 15:55', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 10, 1, 1, TO_DATE('20/02/2015 16:15', 'dd/mm/yyyy hh24:mi'), 3.65)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 16, 1, 3, TO_DATE('20/02/2015 16:23', 'dd/mm/yyyy hh24:mi'), 4.20)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 21, 2, 10, TO_DATE('15/02/2015 16:32', 'dd/mm/yyyy hh24:mi'), 3.55)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 18, 1, 1, TO_DATE('15/02/2015 16:45', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 5, 1, 2, TO_DATE('20/01/2015 16:59', 'dd/mm/yyyy hh24:mi'), 1.88)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 12, 1, 2, TO_DATE('20/01/2015 17:03', 'dd/mm/yyyy hh24:mi'), 2.29)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 24, 1, 1, TO_DATE('20/01/2015 17:13', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 17, 1, 1, TO_DATE('11/01/2015 17:14', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 14, 1, 2, TO_DATE('11/01/2015 17:21', 'dd/mm/yyyy hh24:mi'), 1.90)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 25, 1, 5, TO_DATE('11/01/2015 17:25', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 12, 2, 2, TO_DATE('22/03/2015 17:30', 'dd/mm/yyyy hh24:mi'), 3.00)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 9, 2, 2, TO_DATE('22/03/2015 17:43', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 15, 2, 4, TO_DATE('22/03/2015 17:47', 'dd/mm/yyyy hh24:mi'), 4.65)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 7, 2, 1, TO_DATE('27/02/2015 17:54', 'dd/mm/yyyy hh24:mi'), 1.11)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 23, 2, 2, TO_DATE('01/02/2015 17:57', 'dd/mm/yyyy hh24:mi'), 2.80)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 6, 2, 3, TO_DATE('02/02/2015 18:01', 'dd/mm/yyyy hh24:mi'), 2.35)

INSERT INTO SALES 
VALUES (SALE_ID_SEQ.NEXTVAL, 11, 2, 1, TO_DATE('07/02/2015 18:11', 'dd/mm/yyyy hh24:mi'), 2.80)
