//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketsChain.Helpers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;User Id=TEAM_CRUX;Password=123;")]
        public string OracleConnectionString {
            get {
                return ((string)(this["OracleConnectionString"]));
            }
            set {
                this["OracleConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Populate-Oracle-Db.sql")]
        public string OracleSqlScriptLocation {
            get {
                return ((string)(this["OracleSqlScriptLocation"]));
            }
            set {
                this["OracleSqlScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Vendor-Expenses.xml")]
        public string XmlExpensesLocation {
            get {
                return ((string)(this["XmlExpensesLocation"]));
            }
            set {
                this["XmlExpensesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Aggregated-Sales-Report.pdf")]
        public string PdfSalesReportLocation {
            get {
                return ((string)(this["PdfSalesReportLocation"]));
            }
            set {
                this["PdfSalesReportLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Sales-by-Vendors-Report.xml")]
        public string XmlSalesByVendorLocation {
            get {
                return ((string)(this["XmlSalesByVendorLocation"]));
            }
            set {
                this["XmlSalesByVendorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Verdana.ttf")]
        public string VerdanaFontLocation {
            get {
                return ((string)(this["VerdanaFontLocation"]));
            }
            set {
                this["VerdanaFontLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost:27017")]
        public string MongoDbConnectionString {
            get {
                return ((string)(this["MongoDbConnectionString"]));
            }
            set {
                this["MongoDbConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupermarketsChain")]
        public string DefaultDbName {
            get {
                return ((string)(this["DefaultDbName"]));
            }
            set {
                this["DefaultDbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Json-Reports\\")]
        public string JsonReportsFolder {
            get {
                return ((string)(this["JsonReportsFolder"]));
            }
            set {
                this["JsonReportsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Populate-SqLite-Db.sql")]
        public string SqLiteSqlScriptLocation {
            get {
                return ((string)(this["SqLiteSqlScriptLocation"]));
            }
            set {
                this["SqLiteSqlScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=..\\..\\..\\Helper.Files\\SupermarketsChain.sqlite")]
        public string SqLiteConnectionString {
            get {
                return ((string)(this["SqLiteConnectionString"]));
            }
            set {
                this["SqLiteConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Sales-Reports.zip")]
        public string SalesReportsZipFile {
            get {
                return ((string)(this["SalesReportsZipFile"]));
            }
            set {
                this["SalesReportsZipFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Create-MySql-Schema.sql")]
        public string MySqlScriptLocation {
            get {
                return ((string)(this["MySqlScriptLocation"]));
            }
            set {
                this["MySqlScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;User ID=root;Password=")]
        public string MySqlConnectionString {
            get {
                return ((string)(this["MySqlConnectionString"]));
            }
            set {
                this["MySqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Helper.Files\\Financial-Results.xlsx")]
        public string ExcelReportLocation {
            get {
                return ((string)(this["ExcelReportLocation"]));
            }
            set {
                this["ExcelReportLocation"] = value;
            }
        }
    }
}
